import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import Footer from "@/components/shared/footer";
import StickyIcon from "@/components/shared/sticky-icon";
import Banner from "@/components/shared/banner";
import "../globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider>
            <div className="h-screen w-screen overflow-hidden overflow-y-scroll min-h-screen">
                <main className="flex-1 relative">
                    {/* <StickyIcon /> */}
                    <div className="">
                        {children}
                    </div>
                    <Footer />
                </main>
            </div>
        </SidebarProvider>
    );
}
