import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import Footer from "@/components/shared/footer";
import "../../globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider >
            <div className="h-screen w-screen overflow-x-hidden min-h-screen">
                <main className="flex-1 relative flex flex-col h-full">
                    <div className="flex-1">
                        {children}
                    </div>
                    <Footer />
                </main>
            </div>
        </SidebarProvider>
    );
}
