import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import Footer from "@/components/shared/footer";
import StickyIcon from "@/components/shared/sticky-icon";
import Banner from "@/components/layout/home/banner";
import "../globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="grid grid-cols-12 h-screen w-screen overflow-hidden min-h-screen">
        <div className="xl:col-span-2 col-span-0">
          <AppSidebar />
        </div>
        <div className="flex flex-col w-full xl:col-span-10 col-span-12 overflow-x-hidden  overflow-y-auto">
          <main className="flex-1 relative">
            <StickyIcon />
            <Banner />
            <div className="container-padding">
              {children}
            </div>
            <Footer />
          </main>
        </div>
      </div>
    </SidebarProvider>
  );
}
