import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import Footer from "@/components/shared/footer";
import StickyIcon from "@/components/shared/sticky-icon";
import Banner from "@/components/layout/home/banner";
import "../globals.css"

const quicksand = Quicksand({
    subsets: ["latin"],
    variable: "--font-quicksand",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProductLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Banner height={200} />
            <div className="">
                {children}
            </div>
        </div>
    );
}
