import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import Footer from "@/components/shared/footer";
import StickyIcon from "@/components/shared/sticky-icon";
import Banner from "@/components/shared/banner";
import "../globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider>
            <div className="h-screen w-screen flex overflow-hidden min-h-screen">
                <div className="">
                    <AppSidebar />
                </div>
                <div className="flex flex-col w-full col-span-5 overflow-x-hidden overflow-y-auto">
                    <main className="flex-1 relative">
                        <StickyIcon />
                        <Banner height={200} />
                        <div className="container-padding">
                            {children}
                        </div>
                        <Footer />
                    </main>
                </div>
            </div>
        </SidebarProvider>
    );
}
