import type { Metadata } from "next";
import "../globals.css"
import { SidebarProvider } from "@/components/ui/sidebar";
import { AdminSideBar } from "@/components/shared/admin-sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider>
            <AdminSideBar />
            <div className="container-padding pt-8 w-full">
                {children}
            </div>
        </SidebarProvider>
    );
}
